### ISSUE TITLE
Issues in the last two commits

### ISSUE THREAD

**Issue by SFarida** [MMGGYY66/my-portfolio-website#12]
Hello, while your code looks great and is working as expected please kindly checkout these comments on your last two commits ([1](https://github.com/MMGGYY66/my-portfolio-website/commit/1e54cc7a6e62ee458ed03435edd37cd5866d15f2), [2](https://github.com/MMGGYY66/my-portfolio-website/commit/6602d01565d130544b9d11a49c9da6c48fbc4a3b))

### Highlights

 @SFarida
- Kindly check that there is no space in your class names attributes for best practice on line 32 and 34.
@kensteph
- I examined your code. You did a great work! Please kindly consider refactoring your code in the index.js file 1- Line 37,43 : I think it would be better if you do it like you did for line 41. By doing this you will Don't Repeat Yourself.
@edahigure
- The code is working well. Maybe just to find out why the events only work with arrow functions.

**Comment by MMGGYY66** [comment]
Thank you. I fixed the issues.
