### ISSUE TITLE
Morning session code review

### ISSUE THREAD

**Issue by dennis-every** [MMGGYY66/my-portfolio-website#3]
Highlights:

- Good  use of semantic tags
- Added class clear after float
- Follows well the microverse readme template

Recommendations:

- Remove comments in code - but left there due to instructions to revert back to original code
- Comments explain what is done, not why - but left there due to instructions to revert back to original code
- Commit message: add new changes not descriptive, use git amend message

**Comment by MMGGYY66** [comment]
Thank you all
