### ISSUE TITLE
Peer to peer code review block 3- module 1

### ISSUE THREAD

**Issue by NelsonAraujo93** [MMGGYY66/my-portfolio-website#8]
#7 

Nelson 
 **Highlights:**
1. Add real media links in the Introduction section.
2. Git flow.
3. Linters checkers.
4. Good master presentation.

Edahi
 **Highlights:**
1. Fullfill the requirements.

Lawrence
 **Highlights:**
1. It is look amaizing.
2. Good Git flow practices.

**Comment by MMGGYY66** [comment]
thank you all
